### ISSUE TITLE
Issue visualising Application dependencies using kustomization files

### ISSUE THREAD

**Issue by vkryzh** [flux-subsystem-argo/flamingo#11]
Hi, trying to get some idea on proper Flamingo usage for our use-case, but stuck in the beginning.
I have the next basic file structure. And using kustomize overlays to get code as dry as possible

```
├── infrastructure
│   ├── base
│   ├── development
│   ├── etc
│   └── [etc]
└── apps/etc
```

in base folder I have keda `helmrelease.yaml`

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
spec:
  interval: 24h
  chart:
    spec:
      chart: keda
      version: "2.7.2"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
```

and `kustomization.yaml`

```
resources:
  - helmrelease.yaml
```

In development I have only `kustomization.yaml`

```
namespace: operators
resources:
  - ../../base/keda
```

I have install Argo with FSA and created the next application config:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  destination:
    namespace: operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infrastructure/development/keda
    repoURL: https://github.com/org/repo
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - FluxSubsystem=true
```

As a result I have application created, but no dependencies (even bare helmrelease) present.

<img width="1657" alt="Screenshot 2022-10-13 at 11 42 56" src="https://user-images.githubusercontent.com/10234652/195576541-3ea6c5ac-faed-4522-97a3-2be91e6d4d5a.png">

I want to have some object tree to be present. What am I doing wrong?
