### ISSUE TITLE
[feature] Can flamingo generate flux fields like dependsOn/healthChecks

### ISSUE THREAD

**Issue by mhumeSF** [flux-subsystem-argo/flamingo#22]
Is there a way to markup argocd applications to generate kustomize.toolkit.fluxcd.io manifests with fields like dependsOn and healthChecks?

**Comment by chanwit** [comment]
Hi @mhumeSF 

We've been working on a feature that will allow you to specify templates (in a form of `ConfigMap`) to generate Kustomization objects. But if it's not what you're looking for, maybe we would think of somethings like adding annotations support for those fields?

what do you think?

**Comment by mhumeSF** [comment]
@chanwit Yes, I'd be curious about either the ConfigMap or annotations solutions.

**Comment by chanwit** [comment]
Planned to support the following annotations

```yaml
metadata:
  annotations:
    flux.kustomization/dependsOn: app-1, app-2, app3
    flux.kustomization/healthChecks: Deployment/workload-1, Deployment/workload-2
    flux.kustomization/wait: true
    flux.kustomization/interval: 50m
    flux.kustomization/retryInterval: 15s

metadata:
  annotations:
    flux.helmrelease/interval: 50m
    flux.helmrelease/retryInterval: 15s
```
