### ISSUE TITLE
Flamingo Only Seems to Create Kustomizations

### ISSUE THREAD

**Issue by reedjosh** [flux-subsystem-argo/flamingo#24]
I feel there's a lack of documentation on how to actually use Flamingo. That may be why I'm currently unable to get Flamingo to work as below.

I want to create an Argo application that creates a Flux HelmRelease.

Really I just want the full Helm functionality that Flux has but we're heavily invested in Argo, so I want it to be as transparent as possible.

I create the following Argo application...

``` YAML
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuers
  namespace: argo-cd
spec:
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - FluxSubsystem=true
    - AutoCreateFluxResources=true
    automated:
      prune: true
      selfHeal: true
  project: ""
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    path: ./
    repoURL: https://<redacted-repo-url>/cert-issuers.git
    targetRevision: HEAD
    helm:
      releaseName: cert-issuers
```

Yet, I get a

``` yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
...
...
```
object.

Also, I'm not sure how to pass repo credentials specifications through to the created Flux objects.

![image](https://github.com/flux-subsystem-argo/flamingo/assets/9508385/84a02c5e-9cb9-4e41-9b67-825d08a81a3b)

I can give creds to the repo via the command line, but they just get wiped out by the created git repo resource.

Ideally the Flux repo would be able to pull creds from Argo, but it doesn't seem to do much in this regard.

And again, I don't know where to look for docs on these relationships.
