### ISSUE TITLE
show kustomize resources on argo-ui

### ISSUE THREAD

**Issue by haarchri** [flux-subsystem-argo/flamingo#5]
thanks for this nice work ;)
for helm-charts it is working very good 

we have a kustomization but the resources not showed up in the ui - is this expected ? did i need to setup something more ?

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-aws
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./
    repoURL: flux://loopback
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
```

```
  inventory:
    entries:
      - id: _crossplane-aws_pkg.crossplane.io_ControllerConfig
        v: v1alpha1
      - id: _crossplane-aws_pkg.crossplane.io_Provider
        v: v1
```

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/21083497/157853274-2f8455f3-a399-4f83-a93d-db890c8c2d9e.png">
