### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by devantler** [flux-subsystem-argo/flamingo#70]
I noticed it's been 5 months since the last commit. What is the status of this project? 👀

**Comment by kingdonb** [comment]
The sentiment I've heard expressed privately from some Flux developers is that Flamingo basically killed Weave GitOps. I don't think anyone feels motivated to work on it now.

Active, no. Viable, perhaps? I'm working on the Flux Headlamp plugin, which is still pre-release and not yet ready for publish.

Can I ask you a few questions about your use case? Are you transitioning from Argo to Flux, trying to use both alongside, or ... ?

**Comment by devantler** [comment]
I kinda suspected something in that terms, as I noticed the timeline was close to that. Sad to hear that might be the case. Flamingo looked like a promising way to bridge the two.

However, I am looking into different options to serve tenants with either Flux or ArgoCD workflows in a nice way. I saw Flamingo a while back, and wanted to try it out, when I noticed the lack of commits recently.

Definitely not switching, as I have always favored the code-first approach, the non-monolithic setup, and the near native feel that flux excels at :-)

**Comment by kingdonb** [comment]
The headlamp plugin for flux is really promising, I may have oversold the extent to which I'm working on it, but I was able to deploy it (you still have to build it yourself, when it's finished it will go in a catalog and you can click-to-install AFAIK)

It works nicely for the most part, there are still some gaps, but we're going to try to close them. There are a lot of people involved! I think it feels promising.

**Comment by devantler** [comment]
That's interesting! I am a bit biased by my love for K9s, and my vengeance against click-ops, but I can definitely see some use cases for a read-only UI. It is quite easy to explain GitOps at a high-level, but when you dive into it, it can be a different story. So having a UI that could be pulled out to help alleviate that would be nice.

How does it compare/place it self to e.g.

- [https://github.com/gimlet-io/capacitor](Capacitor)
- [https://github.com/weaveworks/weave-gitops?tab=readme-ov-file](Weave GitOps)

The last one might be a dead project too 🤷🏻‍♂️

**Comment by kingdonb** [comment]
It's heavily inspired by Weave GitOps. (The Flux plugin anyway)

Headlamp is a bigger project, with many integrations. I guess there is a Prometheus plugin. IDK, I've only been focused on the OIDC support and the Flux plugin so far.

Yes, Weave GitOps has been removed from all the critical paths in Flux docs. It's open source though, (and so is Weave GitOps Enterprise! A silver lining) - we've heard of at least one Flux enthusiast who has gone to the lengths to install WGE, after the Weavepocalypse - frankly we didn't even expect our actual customers to install WGE on their own, the CAPI dependencies made it a thing that required special handling and guaranteed assistance.

As you'd expect for an enterprise product...

**Comment by devantler** [comment]
Aha, that makes sense yeah. Well it sounds like Headlamp + the plugin is something I should try out 👀 Will join the conversation over at [headlamp-k8s](https://github.com/headlamp-k8s) if I have something to add 🙂

**Comment by sule26** [comment]
@kingdonb Do you think there’s a chance of Flamingo becoming active again? Being able to use the ArgoCD UI and the Helmfile plugin without the downside of losing the HelmReleases is awesome.

**Comment by christensenjairus** [comment]
I'm also wondering about the state of this project. It seems to be exactly what I'm looking for. It works very well for my use case.

I want to create Argo ApplicationSets with the `cluster` generator and go template syntax for variables, but still be able to use Flux-native HelmReleases. I'd like the HelmReleases so that I can continue to combine Helm, Kustomizations, and kustomization patches like I would in any Flux repo.

Flux + Argo gives me the best of both worlds by being able to use go template kustomization patches like this

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-storage
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'infra-storage-{{.nameNormalized}}'
      namespace: argocd
    spec:
      destination:
        namespace: rook-ceph-external
        name: '{{.nameNormalized}}'
      project: default
      source:
        path: storage
        repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
        targetRevision: main
        kustomize:
          patches:
            - target:
                kind: VolumeSnapshotClass
                name: k8s-rbd
              patch: |-
                - op: replace
                  path: /parameters/clusterID
                  value: '{{.metadata.annotations.radosNamespaceClusterID}}'
```

And using kustomizations with embedded helm releases like this

<img width="288" alt="Screenshot 2024-12-27 at 10 39 16 PM" src="https://github.com/user-attachments/assets/8978b04d-4ef3-44ea-bf1d-06fbab1c026d" />


Anyway, Flamingo is pretty perfect for what I need, but I'm hesitant to use it if it's not supported by at least a small community.
