### ISSUE TITLE
How to list HelmRelease created objects on Argo Application

### ISSUE THREAD

**Issue by drazul** [flux-subsystem-argo/flamingo#8]
Hi, 
I'm testing flamingo and there are some pieces missing in my mind.

Is it possible to list objects created by Helm Operator?

I defined 3 objects: HelmRepository, HelmRelease, and Application (for flux).

This will make Flux deploy the app defined in the HelmRelease and the Application will make Argo list the application. But for some reason, all those created objects are not listed in the ArgoCD application. Am I missing something? Do I need to define some labels or annotations in created objects?

Another issue is argo is only listing applications defined on argocd namespace, but I guess it's something with the default config.

Here are the three files I'm defining:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: argocd
spec:
  interval: 1m
  url: https://stefanprodan.github.io/podinfo
```
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: 6.1.5
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: argocd
      interval: 1m
  values:
    replicaCount: 2
```
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./demo/artifacts/flux-apps/podinfo
    repoURL: https://github.com/drazul/flamingo-test
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - FluxSubsystem=true
```

**Comment by kingdonb** [comment]
> Is it possible to list objects created by Helm Operator?

Assuming you meant Helm Controller, yes... ish. If you can trust the chart to write its namespaced resources only within one namespace, or if you change your config to enforce this through `HelmRelease.spec.targetNamespace` then you can enumerate all the resources the HelmRelease creates through reading the labels that it applies in convention with the behavior of Helm CLI.

We did not find a good way to list all resources other than to query `api-resources` to find out the total enumeration of all resource kinds on the cluster, and then construct a query with each of them (abbreviated because I have a lot of CRDs on my cluster):

```
kubectl get componentstatuses,configmaps,endpoints,events,...,helmrepositories.source.toolkit.fluxcd.io,csidrivers.storage.k8s.io,csinodes.storage.k8s.io,csistoragecapacities.storage.k8s.io,storageclasses.storage.k8s.io,volumeattachments.storage.k8s.io -l helm.toolkit.fluxcd.io/name=kube-oidc-proxy -n kube-oidc-proxy
```

Because some resources are not namespaced, those resources avoid the namespace and query the cluster instead. The other resources are namespaced, and any in the Release.namespace can be retrieved most efficiently by the label.

I have this recent experience from a separate project that I'm working on, the [Flux VSCode extension](https://github.com/weaveworks/vscode-gitops-tools), where we have just approached solving this problem again as a Weaveworks project – so the limitations as I perceive them are from my work on that implementation, as a side-note.

In the VSCode extension, we also have a feature that does iterate through Flux resources and presents their children in a tree. A problem I suspect might come in when helm charts do not follow the tenant best practices and create resources outside of their namespace. I can't think of any practical examples or actual charts who do this but as a theoretical concern, if your HelmRelease does not set `targetNamespace` and the chart decides to create in namespace `otherns` then it will be very difficult to track down those resources. Helm controller can force the chart to put its namespaced resources in target.

But as I've said, I have never seen a chart do this, only as a theoretical concern.

> Do I need to define some labels or annotations in created objects?

Label is indexed as I understand it, so more efficient to query from than an annotation. (This distinction I'm attributing as a reference [to the Kubernetes docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#attaching-metadata-to-objects), which state "You can use either labels or annotations to attach metadata to Kubernetes objects. Labels can be used to select objects and to find collections of objects that satisfy certain conditions. In contrast, annotations are not used to identify and select objects" – I'm not expert in how it works though.)

The annotations are set by Helm upstream and the labels are created by Helm Controller. Every HelmRelease has a `spec.releaseName` either inferred from the default (`namespace-helmreleasename`) or set explicitly in a source manifest.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: kube-oidc-proxy              ## annotations
    meta.helm.sh/release-namespace: kube-oidc-proxy
  labels:
    app.kubernetes.io/instance: kube-oidc-proxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-oidc-proxy
    app.kubernetes.io/version: v1.0.0
    helm.sh/chart: kube-oidc-proxy-0.3.2
    helm.toolkit.fluxcd.io/name: kube-oidc-proxy              ## labels
    helm.toolkit.fluxcd.io/namespace: flux-system
```

So for this HelmRelease, which sets `targetNamespace` and `storageNamespace` to the same value, also per best practice, the `releaseName` is set to `kube-oidc-proxy` and the `targetNamespace` is `kube-oidc-proxy` so as also with the same value for `storageNamespace`. You can see what labels and annotations that resulted in with my example above.

The `HelmRelease` is resident in `flux-system` namespace for access to some secrets I have decided to keep in there.

If you do not set targetNamespace then the release namespace is inferred by default to be the same namespace that `HelmRelease` is in.
